version: '3'

services:
  db:
    image: postgres:alpine
    container_name: treasure-hunting_db
    restart: always
    volumes:
      - ./var/postgresql/data:/var/lib/postgresql/data

  app:
    build: .
    container_name: treasure-hunting_app
    restart: always
    environment:
      - HTTP_HOST=app
      - HTTP_PORT=80
      - DATABASE_ENGINE=django.db.backends.postgresql_psycopg2
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    ports:
      - 8000:80
    links:
      - db
