# Generated by Django 2.2.4 on 2019-09-09 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='name',
            field=models.CharField(max_length=6),
        ),
        migrations.AddField(
            model_name='difficulty',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treasure.Goal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='difficulty',
            name='quizzes',
            field=models.ManyToManyField(to='treasure.Quiz'),
        ),
        migrations.AddField(
            model_name='player',
            name='quizzes',
            field=models.ManyToManyField(to='treasure.Quiz'),
        ),
    ]
