# Generated by Django 2.2.4 on 2019-09-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_auto_20190909_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='quizzes',
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz1', to='treasure.Quiz')),
                ('quiz2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz2', to='treasure.Quiz')),
                ('quiz3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz3', to='treasure.Quiz')),
                ('quiz4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz4', to='treasure.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='quizzes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='treasure.Quizzes'),
        ),
    ]
