# Generated by Django 2.2.4 on 2019-09-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0003_auto_20190916_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasure.Quiz')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='quizzes',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
        migrations.AddField(
            model_name='player',
            name='quizzes',
            field=models.ManyToManyField(to='treasure.QuizData'),
        ),
    ]
