# Generated by Django 2.2.4 on 2019-09-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0004_auto_20190917_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
